#!/usr/bin/python
'''
General plan:
    use scikits.audiolab to get data bit by bit
    fft the samples --> get the spectrum
'''
import numpy as np
from functools import reduce
from scikits.audiolab import Sndfile
import sys

####### VARIABLES/FUNCTIONS OF DOOM

#for future, pass the uri to the script
audio_file = "/home/cz/test.wav"

# number of bands
bands = 50 

#fouriers per second of sample 
fouriers_per_second = np.float(10)

#the window size (i.e., number of samples) for each fft
fourier_window = np.float(512)


def fft(samples):
    #abs of fast fourier transform
    return np.abs(np.fft.rfft(samples)) 

def bandwidth(sample_size, sample_rate):
    #return bandwidth
    return np.multiply(np.true_divide(2, sample_size), np.true_divide(sample_rate, 2))

def freq_to_i(frequency, sample_size, sample_rate):
    #return index given frequency
    freq = np.float(frequency)
    ss = np.float(sample_size)
    sr = np.float(sample_rate)
    if freq < np.true_divide(bandwidth(ss, sr), 2):
        return 0
    
    if freq > np.true_divide(sr, 2) - np.true_divide(bandwidth(ss, sr), 2):
        return np.floor_divide(ss, 2)

    f = np.true_divide(freq, sr)
    i = np.round(np.multiply(ss, f))
    return int(i)

def log_averages(spectrum, sample_size, sample_rate, bands = 12):
    #given spectrum, average the frequency amplitudes into
    #<bands> number of frequency bands
    sr = np.float(sample_rate)
    averages = []
    for i in range(bands):
        avg = np.float(0)
        if i == 0:
            low_freq = 0
        else:
            low_freq = np.true_divide(np.true_divide(sr,2), np.power(2, bands - i))

        high_freq = np.true_divide(np.true_divide(sr,2), np.power(2, bands - 1 - i))
        

        low_b = freq_to_i(low_freq, sample_size, sample_rate)
        hi_b = freq_to_i(high_freq, sample_size, sample_rate)

        #print i, (low_b, hi_b), (low_freq,high_freq)

        for j in range(low_b, int(hi_b) +1):
            avg += spectrum[j]
        avg = np.true_divide(avg, hi_b - low_b + 1)
        averages.append(avg)

    return np.array(averages)

###### END VARIABLES/FUNCTIONS OF DOOM

########### GET THE AUDIO DATA

f = Sndfile(audio_file, "r")

# some germane
# f properties..
    #   samplerate = samplerate of the file
    #   nframes = total number of frames in the file
    #   channels = number of channels in the file
#   methods...
    #   read_frames(x) = read x number of frames, moves index
    #   seek(x) = move to frame number x

#frame step between each fft
fourier_step = np.multiply(np.reciprocal(fouriers_per_second), f.samplerate)

# print the info, if one wants
print "samplerate:",f.samplerate
print "total frames:",f.nframes
print "window_size:",fourier_window
print "# of ffts:", np.true_divide(f.nframes,fourier_step)
print "step:",fourier_step
print "length:", f.nframes / f.samplerate, "seconds"

# go through parts of file, chunk by chunk, with seeks
i=0
spectrum_data = []
for window in range(int(np.floor_divide(f.nframes, fourier_step))):
    f.seek(i)
    if f.channels == 1:
        chunk = f.read_frames(fourier_window)

    else:
        #average the channels
        chunk = []
        for frame in f.read_frames(fourier_window):
            avg = np.true_divide(np.sum(frame), fourier_window)
            chunk.append(avg)
    
    spectrum_data.append(fft(chunk))
    i+=fourier_step

# Have spectrum data in array, yay!!!!

# average the shit into w/e number of bands
a = [log_averages(s, fourier_window, f.samplerate, bands) for s in spectrum_data]


# we are going to write to a file
#import json
from StringIO import StringIO
fp = StringIO()

# write part of desired format, 
# probably can do this through json.dump
# but fucked if i know how
fp.write("data[0] = {title: 'blar', timecode: [")

# calculate very roughly millisecond difference b/w each sample
time_step = np.reciprocal(fouriers_per_second) * 1000
#print time_step, "ms b/w each sampling"

# time window for each sample set
window_time = ((f.nframes / f.samplerate) / fourier_window) * 1000
#print window_time, "ms for each sample set"

for k,v in enumerate(a):
    # calculte time (in ms) for each sample
    time = int(round((k * time_step) + window_time))
    print time, "milliseconds"

    #scale values to between 0-255
    t = v.min()
    scale = float(255) / (v.max() - t)
    tmp = np.subtract(v,t)
    tmp = np.multiply(tmp, scale)
    tmp = np.round(tmp)
    tmp = np.asarray(tmp,dtype=int)

    # write to file object
    fp.write('{t:' + str(time) + ',p:' + str(tmp.tolist()) + '}')
    if k == len(a) - 1:
        continue
    else:
        fp.write(',')

fp.write("]};")
contents = fp.getvalue()
fp.close()

# write to file
with open("/home/cz/d.txt", "w") as p:
    p.write(contents)
